--ĐĂNG NHẬP SYS VỚI XEPDB1 CẤP QUYỀN 

-- Quyền OLS 
GRANT SELECT ANY DICTIONARY TO ADMIN;

GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON SA_POLICY_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON CHAR_TO_LABEL TO ADMIN WITH GRANT OPTION;
GRANT LBAC_DBA TO ADMIN;
GRANT EXECUTE ON SA_SYSDBA TO ADMIN;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN;

-- XÓA USER U1 -> U8 NẾU TỒN TẠI 

BEGIN EXECUTE IMMEDIATE 'DROP USER U1 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U2 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U3 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U4 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U5 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U6 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U7 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER U8 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- TẠO USER U1 -> U8
CREATE USER U1 IDENTIFIED BY 12345;
CREATE USER U2 IDENTIFIED BY 12345;
CREATE USER U3 IDENTIFIED BY 12345;
CREATE USER U4 IDENTIFIED BY 12345;
CREATE USER U5 IDENTIFIED BY 12345;
CREATE USER U6 IDENTIFIED BY 12345;
CREATE USER U7 IDENTIFIED BY 12345;
CREATE USER U8 IDENTIFIED BY 12345;

-- CẤP QUYỀN CHO USER
GRANT CREATE SESSION TO U1;
GRANT CREATE SESSION TO U2;
GRANT CREATE SESSION TO U3;
GRANT CREATE SESSION TO U4;
GRANT CREATE SESSION TO U5;
GRANT CREATE SESSION TO U6;
GRANT CREATE SESSION TO U7;
GRANT CREATE SESSION TO U8;
