--ĐĂNG NHẬP ADMIN VỚI XEPDB1
-- XÓA BẢNG THONGBAO NẾU ĐÃ TỒN TẠI
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
--TẠO BẢNG THÔNG BÁO
create table THONGBAO ( 
    MA_TB     varchar2(10) primary key, 
    NOI_DUNG  varchar2(500) not null, 
    NGAY_GIO  timestamp not null, 
    DIA_DIEM  varchar2(100) not null 
);


-- CẤP QUYỀN SELECT CHO U1 -> U8
GRANT SELECT ON THONGBAO TO U1;
GRANT SELECT ON THONGBAO TO U2;
GRANT SELECT ON THONGBAO TO U3;
GRANT SELECT ON THONGBAO TO U4;
GRANT SELECT ON THONGBAO TO U5;
GRANT SELECT ON THONGBAO TO U6;
GRANT SELECT ON THONGBAO TO U7;
GRANT SELECT ON THONGBAO TO U8;


-- TẠO POLICY

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

BEGIN
    SA_SYSDBA.CREATE_POLICY(
        POLICY_NAME => 'REGION_POLICY',
        COLUMN_NAME => 'REGION_LABEL'
    );
END;
/

EXEC SA_SYSDBA.ENABLE_POLICY('REGION_POLICY');

-- TẠO LEVEL

BEGIN
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 1000, 'NV',  'Nhan vien');
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 2000, 'LDK', 'Lanh dao khoa');
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 3000, 'BGD', 'Ban giam doc');
END;
/

-- TẠO COMPARTMENT

BEGIN
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 10, 'TH', 'Tieu hoa');
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 20, 'TK', 'Than kinh');
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 30, 'TM', 'Tim mach');
END;
/

-- TẠO GROUP

BEGIN
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 100, 'HCM', 'Ho Chi Minh');
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 200, 'HP',  'Hai Phong');
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 300, 'HN',  'Ha Noi');
END;
/

-- TẠO LABEL

BEGIN
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1001, 'NV');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1002, 'BGD');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1003, 'LDK');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1004, 'LDK:TH');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1005, 'NV:TH:HCM');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1006, 'NV:TH:HN');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1007, 'LDK:TH,TK:HP');
END;
/