--ĐĂNG NHẬP ADMIN VỚI XEPDB1
--CHẠY NGAY SAU FILE 02_admin_table_policy.sql
-- PHẢI  DISCONNECT ADMIN RỒI CONNECT lại ADMIN trước khi chạy file này

-- TẠO LEVEL
BEGIN
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 1000, 'NV',  'Nhan vien');
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 2000, 'LDK', 'Lanh dao khoa');
    SA_COMPONENTS.CREATE_LEVEL('REGION_POLICY', 3000, 'BGD', 'Ban giam doc');
END;
/

-- TẠO COMPARTMENT

BEGIN
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 10, 'TH', 'Tieu hoa');
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 20, 'TK', 'Than kinh');
    SA_COMPONENTS.CREATE_COMPARTMENT('REGION_POLICY', 30, 'TM', 'Tim mach');
END;
/

-- TẠO GROUP

BEGIN
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 100, 'HCM', 'Ho Chi Minh');
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 200, 'HP',  'Hai Phong');
    SA_COMPONENTS.CREATE_GROUP('REGION_POLICY', 300, 'HN',  'Ha Noi');
END;
/

-- TẠO LABEL

BEGIN
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1001, 'NV');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1002, 'BGD');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1003, 'LDK');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1004, 'LDK:TH');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1005, 'NV:TH:HCM');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1006, 'NV:TH:HN');
    SA_LABEL_ADMIN.CREATE_LABEL('REGION_POLICY', 1007, 'LDK:TH,TK:HP');
END;
/