-- ĐĂNG NHẬP ADMIN VỚI XEPDB1
-- APPLY POLICY LẦN 1 VỚI NO_CONTROL

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME   => 'REGION_POLICY',
        SCHEMA_NAME   => 'ADMIN',
        TABLE_NAME    => 'THONGBAO',
        TABLE_OPTIONS => 'NO_CONTROL'
    );
END;
/

-- INSERT DỮ LIỆU

INSERT INTO THONGBAO VALUES ('T1', 'Thong bao NV', TIMESTAMP '2025-05-01 08:00:00', 'ALL', NULL);
INSERT INTO THONGBAO VALUES ('T2', 'Thong bao BGD', TIMESTAMP '2025-05-01 09:00:00', 'BGD', NULL);
INSERT INTO THONGBAO VALUES ('T3', 'Thong bao LDK', TIMESTAMP '2025-05-01 10:00:00', 'ALL', NULL);
INSERT INTO THONGBAO VALUES ('T4', 'Thong bao LDK TH', TIMESTAMP '2025-05-01 11:00:00', 'TH', NULL);
INSERT INTO THONGBAO VALUES ('T5', 'NV TH HCM', TIMESTAMP '2025-05-01 12:00:00', 'HCM', NULL);
INSERT INTO THONGBAO VALUES ('T6', 'NV TH HN', TIMESTAMP '2025-05-01 13:00:00', 'HN', NULL);
INSERT INTO THONGBAO VALUES ('T7', 'LDK TH TK HP', TIMESTAMP '2025-05-01 14:00:00', 'HP', NULL);

COMMIT;

-- GÁN LABEL CHO TỪNG DÒNG

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV')
WHERE MA_TB = 'T1';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'BGD')
WHERE MA_TB = 'T2';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK')
WHERE MA_TB = 'T3';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK:TH')
WHERE MA_TB = 'T4';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV:TH:HCM')
WHERE MA_TB = 'T5';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV:TH:HN')
WHERE MA_TB = 'T6';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK:TH,TK:HP')
WHERE MA_TB = 'T7';

COMMIT;

-- REMOVE POLICY

BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
        POLICY_NAME => 'REGION_POLICY',
        SCHEMA_NAME => 'ADMIN',
        TABLE_NAME  => 'THONGBAO'
    );
END;
/

-- APPLY LẠI VỚI READ_CONTROL

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME   => 'REGION_POLICY',
        SCHEMA_NAME   => 'ADMIN',
        TABLE_NAME    => 'THONGBAO',
        TABLE_OPTIONS => 'READ_CONTROL'
    );
END;
/

UPDATE THONGBAO
SET NOI_DUNG = NOI_DUNG;

COMMIT;

-- GÁN LABEL CHO USER

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U1', 'BGD:TH,TK,TM:HCM,HP,HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U2', 'LDK:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U3', 'LDK:TK:HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U4', 'NV:TK:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U5', 'NV:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U6', 'LDK:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U7', 'LDK:TH,TK,TM:HCM,HP,HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'U8', 'NV:TH:HN');
END;
/