-- =====================================================
-- 99_drop_vpd.sql
-- Rollback VPD: drop toàn bộ policy, policy function,
-- và hàm helper fn_get_role.
-- Chạy bằng tài khoản ADMIN (DBA)
-- =====================================================

SET SERVEROUTPUT ON;

-- =====================================================
-- 1. Drop VPD Policies
-- =====================================================
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','HSBA_DV',   'POL_HSBA_DV_KTV');     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','HSBA_DV',   'POL_HSBA_DV_RLS');     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','NHAN_VIEN', 'POL_NHANVIEN_SELF');   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','BENH_NHAN', 'POL_BENHNHAN_SELF');   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','BENH_NHAN', 'POL_BN_RLS');          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','HSBA',      'POL_HSBA_RLS');        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('ADMIN','DON_THUOC', 'POL_DON_THUOC_RLS');   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    DBMS_OUTPUT.PUT_LINE('Đã drop toàn bộ VPD policies.');
END;
/

-- =====================================================
-- 2. Drop Policy Functions
-- =====================================================
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_POLICY_HSBA_DV';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_POLICY_NHANVIEN';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_POLICY_BENHNHAN';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_POLICY_HSBA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_POLICY_DON_THUOC';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION ADMIN.FN_GET_ROLE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Hoàn thành rollback VPD ===');
END;
/
