-- =====================================================
-- 06_drop_rbac.sql
-- Script dọn dẹp tất cả RBAC objects (rollback)
-- Chạy bằng tài khoản ADMIN (DBA)
-- =====================================================

SET SERVEROUTPUT ON;

-- 1. Drop VPD Policies
BEGIN
    DBMS_RLS.DROP_POLICY('ADMIN', 'HSBA_DV', 'POL_HSBA_DV_KTV');
    DBMS_OUTPUT.PUT_LINE('Đã xóa policy POL_HSBA_DV_KTV.');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Policy POL_HSBA_DV_KTV không tồn tại.');
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('ADMIN', 'NHAN_VIEN', 'POL_NHANVIEN_SELF');
    DBMS_OUTPUT.PUT_LINE('Đã xóa policy POL_NHANVIEN_SELF.');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Policy POL_NHANVIEN_SELF không tồn tại.');
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY('ADMIN', 'BENH_NHAN', 'POL_BENHNHAN_SELF');
    DBMS_OUTPUT.PUT_LINE('Đã xóa policy POL_BENHNHAN_SELF.');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Policy POL_BENHNHAN_SELF không tồn tại.');
END;
/

-- 2. Drop Trigger
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_KETQUA';
    DBMS_OUTPUT.PUT_LINE('Đã xóa trigger TRG_AUDIT_KETQUA.');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Trigger TRG_AUDIT_KETQUA không tồn tại.');
END;
/

-- 3. Drop Audit Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_KETQUA CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Đã xóa bảng AUDIT_KETQUA.');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Bảng AUDIT_KETQUA không tồn tại.');
END;
/

-- 4. Drop Policy Functions
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION FN_POLICY_HSBA_DV';
    DBMS_OUTPUT.PUT_LINE('Đã xóa function FN_POLICY_HSBA_DV.');
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION FN_POLICY_NHANVIEN';
    DBMS_OUTPUT.PUT_LINE('Đã xóa function FN_POLICY_NHANVIEN.');
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION FN_POLICY_BENHNHAN';
    DBMS_OUTPUT.PUT_LINE('Đã xóa function FN_POLICY_BENHNHAN.');
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 5. Revoke roles từ tất cả users rồi drop roles
DECLARE
BEGIN
    -- Revoke RL_KYTHUATVIEN từ KTV
    FOR v_i IN 121..170 LOOP
        BEGIN
            EXECUTE IMMEDIATE 'REVOKE RL_KYTHUATVIEN FROM NV' || LPAD(v_i, 4, '0');
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    -- Revoke RL_BENHNHAN từ BN
    FOR v_i IN 1..100000 LOOP
        BEGIN
            EXECUTE IMMEDIATE 'REVOKE RL_BENHNHAN FROM BN' || LPAD(v_i, 6, '0');
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Đã revoke tất cả roles từ users.');
END;
/

-- Drop roles
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE RL_KYTHUATVIEN';
    DBMS_OUTPUT.PUT_LINE('Đã xóa role RL_KYTHUATVIEN.');
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE RL_BENHNHAN';
    DBMS_OUTPUT.PUT_LINE('Đã xóa role RL_BENHNHAN.');
EXCEPTION WHEN OTHERS THEN NULL; END;
/

DBMS_OUTPUT.PUT_LINE('=== Hoàn thành dọn dẹp RBAC ===');
