-- RESET OLS SẠCH 100% (ĐĂNG NHẬP SYS VỚI XEPDB1)

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

-- 1. REMOVE POLICY KHỎI BẢNG 
BEGIN
  SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
    POLICY_NAME => 'REGION_POLICY',
    SCHEMA_NAME => 'ADMIN',
    TABLE_NAME  => 'THONGBAO'
  );
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- 2. DISABLE POLICY
BEGIN
  SA_SYSDBA.DISABLE_POLICY('REGION_POLICY');
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- 3. DROP POLICY 
BEGIN
  SA_SYSDBA.DROP_POLICY(
    POLICY_NAME => 'REGION_POLICY',
    DROP_COLUMN => TRUE
  );
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

COMMIT;

