--ĐĂNG NHẬP SYS VỚI XEPDB1 CẤP QUYỀN 

-- Quyền OLS 
GRANT SELECT ANY DICTIONARY TO ADMIN;

GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON SA_POLICY_ADMIN TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON CHAR_TO_LABEL TO ADMIN WITH GRANT OPTION;
GRANT LBAC_DBA TO ADMIN;
GRANT EXECUTE ON SA_SYSDBA TO ADMIN;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN;
