--ĐĂNG NHẬP ADMIN VỚI XEPDB1
-- XÓA BẢNG THONGBAO NẾU ĐÃ TỒN TẠI
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
--TẠO BẢNG THÔNG BÁO
create table THONGBAO ( 
    MA_TB     varchar2(10) primary key, 
    NOI_DUNG  varchar2(500) not null, 
    NGAY_GIO  timestamp not null, 
    DIA_DIEM  varchar2(100) not null 
);


GRANT SELECT ON THONGBAO TO NV0001;
GRANT SELECT ON THONGBAO TO NV0021;
GRANT SELECT ON THONGBAO TO NV0022;
GRANT SELECT ON THONGBAO TO NV0121;
GRANT SELECT ON THONGBAO TO NV0122;
GRANT SELECT ON THONGBAO TO NV0002;
GRANT SELECT ON THONGBAO TO NV0003;
GRANT SELECT ON THONGBAO TO NV0123;

-- TẠO POLICY

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

BEGIN
    SA_SYSDBA.CREATE_POLICY(
        POLICY_NAME => 'REGION_POLICY',
        COLUMN_NAME => 'REGION_LABEL'
    );
END;
/

EXEC SA_SYSDBA.ENABLE_POLICY('REGION_POLICY');

