-- ĐĂNG NHẬP ADMIN VỚI XEPDB1
-- APPLY POLICY LẦN 1 VỚI NO_CONTROL

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME   => 'REGION_POLICY',
        SCHEMA_NAME   => 'ADMIN',
        TABLE_NAME    => 'THONGBAO',
        TABLE_OPTIONS => 'NO_CONTROL'
    );
END;
/

-- INSERT DỮ LIỆU THÔNG BÁO 

INSERT INTO THONGBAO VALUES (
    'T1',
    N'Họp khẩn toàn thể nhân viên bệnh viện về quy trình ứng phó sự cố',
    TIMESTAMP '2025-05-01 08:00:00',
    'Tất cả cơ sở',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T2',
    N'Họp khẩn Ban giám đốc về kế hoạch điều hành bệnh viện',
    TIMESTAMP '2025-05-01 09:00:00',
    N'Phòng họp Ban giám đốc',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T3',
    N'Họp khẩn dành cho lãnh đạo các khoa về phối hợp chuyên môn',
    TIMESTAMP '2025-05-01 10:00:00',
    N'Tất cả cơ sở',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T4',
    N'Họp khẩn lãnh đạo Khoa Tiêu hóa về phân công nhân sự',
    TIMESTAMP '2025-05-01 11:00:00',
    N'Khoa Tiêu hóa',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T5',
    N'Họp khẩn nhân viên Khoa Tiêu hóa tại cơ sở Hồ Chí Minh',
    TIMESTAMP '2025-05-01 12:00:00',
    N'Cơ sở Hồ Chí Minh',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T6',
    N'Họp khẩn nhân viên Khoa Tiêu hóa tại cơ sở Hà Nội',
    TIMESTAMP '2025-05-01 13:00:00',
    N'Cơ sở Hà Nội',
    NULL
);

INSERT INTO THONGBAO VALUES (
    'T7',
    N'Họp khẩn lãnh đạo Khoa Tiêu hóa và Khoa Thần kinh tại Hải Phòng',
    TIMESTAMP '2025-05-01 14:00:00',
    N'Cơ sở Hải Phòng',
    NULL
);

COMMIT;

-- GÁN LABEL CHO TỪNG DÒNG

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV')
WHERE MA_TB = 'T1';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'BGD')
WHERE MA_TB = 'T2';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK')
WHERE MA_TB = 'T3';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK:TH')
WHERE MA_TB = 'T4';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV:TH:HCM')
WHERE MA_TB = 'T5';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'NV:TH:HN')
WHERE MA_TB = 'T6';

UPDATE THONGBAO
SET REGION_LABEL = CHAR_TO_LABEL('REGION_POLICY', 'LDK:TH,TK:HP')
WHERE MA_TB = 'T7';

COMMIT;

-- REMOVE POLICY

BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
        POLICY_NAME => 'REGION_POLICY',
        SCHEMA_NAME => 'ADMIN',
        TABLE_NAME  => 'THONGBAO'
    );
END;
/

-- APPLY LẠI VỚI READ_CONTROL

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME   => 'REGION_POLICY',
        SCHEMA_NAME   => 'ADMIN',
        TABLE_NAME    => 'THONGBAO',
        TABLE_OPTIONS => 'READ_CONTROL'
    );
END;
/

UPDATE THONGBAO
SET NOI_DUNG = NOI_DUNG;

COMMIT;

-- GÁN LABEL CHO USER

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0001', 'BGD:TH,TK,TM:HCM,HP,HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0021', 'LDK:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0022', 'LDK:TK:HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0121', 'NV:TK:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0122', 'NV:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0002', 'LDK:TM:HCM');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0003', 'LDK:TH,TK,TM:HCM,HP,HN');
    SA_USER_ADMIN.SET_USER_LABELS('REGION_POLICY', 'NV0123', 'NV:TH:HN');
END;
/