-- ---------------------------------------------
-- 00_bootstrap_demo_FIXED.sql
-- Chạy bằng SYS AS SYSDBA hoặc tài khoản tương đương.
-- BẮT BUỘC chạy trong PDB (ví dụ XEPDB1), KHÔNG chạy ở CDB$ROOT.
-- Mục tiêu:
--   1) Tạo admin app ATBM_ADMIN
--   2) Tạo owner LAB_OWNER với object mẫu
--   3) Tạo một số user/role test cho phân hệ 1
-- ---------------------------------------------

SET DEFINE OFF;
SET SERVEROUTPUT ON;

BEGIN DBMS_OUTPUT.PUT_LINE('0. Kiem tra container hien tai'); END;
/
DECLARE
  v_con_name VARCHAR2(128);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'CON_NAME') INTO v_con_name FROM dual;
  IF v_con_name = 'CDB$ROOT' THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Hay chay script trong PDB (vi du XEPDB1), khong chay trong CDB$ROOT.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('Dang chay trong container: ' || v_con_name);
END;
/

BEGIN DBMS_OUTPUT.PUT_LINE('1. Xoa user/role cu neu ton tai'); END;
/

BEGIN
  FOR r IN (
    SELECT username
    FROM dba_users
    WHERE username IN ('ATBM_ADMIN','LAB_OWNER','DEV_A','DEV_B','APP_USER1','APP_USER2')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP USER ' || r.username || ' CASCADE';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR r IN (
    SELECT role
    FROM dba_roles
    WHERE role IN ('RL_READONLY','RL_ANALYST','RL_PROGRAM')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP ROLE ' || r.role;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN DBMS_OUTPUT.PUT_LINE('2. Tao users'); END;
/

CREATE USER ATBM_ADMIN IDENTIFIED BY "Admin#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ATBM_ADMIN;
GRANT DBA TO ATBM_ADMIN;
GRANT SELECT ANY DICTIONARY TO ATBM_ADMIN;
GRANT CREATE PROCEDURE TO ATBM_ADMIN;
GRANT EXECUTE ON DBMS_RLS TO ATBM_ADMIN;

CREATE USER LAB_OWNER IDENTIFIED BY "Lab#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO LAB_OWNER;

CREATE USER DEV_A IDENTIFIED BY "Dev#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE USER DEV_B IDENTIFIED BY "Dev#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE USER APP_USER1 IDENTIFIED BY "App#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE USER APP_USER2 IDENTIFIED BY "App#12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO DEV_A, DEV_B, APP_USER1, APP_USER2;

BEGIN DBMS_OUTPUT.PUT_LINE('3. Tao roles'); END;
/

CREATE ROLE RL_READONLY;
CREATE ROLE RL_ANALYST;
CREATE ROLE RL_PROGRAM;

BEGIN DBMS_OUTPUT.PUT_LINE('4. Tao object mau trong schema LAB_OWNER'); END;
/
ALTER SESSION SET CURRENT_SCHEMA = LAB_OWNER;

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
    LOCATION_NAME VARCHAR2(100)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(120),
    PHONE_NUMBER VARCHAR2(30),
    DEPARTMENT_ID NUMBER REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    SALARY NUMBER(12,2),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_NAME) VALUES (10, 'IT', 'HCM');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_NAME) VALUES (20, 'HR', 'HN');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_NAME) VALUES (30, 'Finance', 'HP');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FULL_NAME, EMAIL, PHONE_NUMBER, DEPARTMENT_ID, SALARY, STATUS)
VALUES (1, 'Nguyen Van A', 'a@example.com', '0900000001', 10, 15000000, 'ACTIVE');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FULL_NAME, EMAIL, PHONE_NUMBER, DEPARTMENT_ID, SALARY, STATUS)
VALUES (2, 'Tran Thi B', 'b@example.com', '0900000002', 20, 18000000, 'ACTIVE');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FULL_NAME, EMAIL, PHONE_NUMBER, DEPARTMENT_ID, SALARY, STATUS)
VALUES (3, 'Le Van C', 'c@example.com', '0900000003', 30, 20000000, 'INACTIVE');

CREATE OR REPLACE VIEW VW_EMP_SUMMARY AS
SELECT e.EMPLOYEE_ID,
       e.FULL_NAME,
       d.DEPARTMENT_NAME,
       e.SALARY,
       e.STATUS
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

CREATE OR REPLACE PROCEDURE PR_RAISE_SALARY(
    p_employee_id IN NUMBER,
    p_amount      IN NUMBER
) AS
BEGIN
    UPDATE EMPLOYEES
       SET SALARY = NVL(SALARY, 0) + p_amount
     WHERE EMPLOYEE_ID = p_employee_id;
END;
/

CREATE OR REPLACE FUNCTION FN_EMP_COUNT(
    p_department_id IN NUMBER
) RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM EMPLOYEES
     WHERE DEPARTMENT_ID = p_department_id;
    RETURN v_count;
END;
/

COMMIT;
ALTER SESSION SET CURRENT_SCHEMA = SYS;

BEGIN DBMS_OUTPUT.PUT_LINE('5. Cap mot it quyen nen de co du lieu demo ban dau'); END;
/

GRANT SELECT ON LAB_OWNER.DEPARTMENTS TO RL_READONLY;
GRANT SELECT ON LAB_OWNER.VW_EMP_SUMMARY TO RL_ANALYST;
GRANT EXECUTE ON LAB_OWNER.PR_RAISE_SALARY TO RL_PROGRAM;
GRANT EXECUTE ON LAB_OWNER.FN_EMP_COUNT TO RL_PROGRAM;

GRANT RL_READONLY TO DEV_A;
GRANT RL_ANALYST TO DEV_B;
GRANT RL_PROGRAM TO APP_USER1;

BEGIN
    DBMS_OUTPUT.PUT_LINE('6. Tao package PKG_ADMIN trong schema ATBM_ADMIN');
    DBMS_OUTPUT.PUT_LINE('Buoc tiep theo: ket noi bang ATBM_ADMIN va chay PROCEDURE.sql');
    DBMS_OUTPUT.PUT_LINE('  sql ATBM_ADMIN/"Admin#12345"@localhost:1521/XEPDB1');
    DBMS_OUTPUT.PUT_LINE('  @database/PROCEDURE.sql');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Hoan tat bootstrap.');
    DBMS_OUTPUT.PUT_LINE('Tai khoan app: ATBM_ADMIN / Admin#12345');
    DBMS_OUTPUT.PUT_LINE('Schema object mau: LAB_OWNER / Lab#12345');
END;
/
