-- =====================================================
-- 02_grant_ktv_bn.sql
-- RBAC + View cho 2 role:
--   RL_KYTHUATVIEN  (TC#4 + TC#5)
--   RL_BENHNHAN     (TC#5)
--
-- KTV và BN KHÔNG được grant trực tiếp trên base table.
-- Tầng lọc dòng nằm trong view theo SESSION_USER.
-- WITH CHECK OPTION chặn thao tác làm dòng thoát khỏi view.
-- Chạy bằng tài khoản ADMIN (DBA)
-- =====================================================

SET SERVEROUTPUT ON;

-- =====================================================
-- 1. Thu hồi grant trực tiếp cũ trên base table nếu đã từng cài đặt
-- =====================================================
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT ON ADMIN.HSBA_DV FROM RL_KYTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE UPDATE ON ADMIN.HSBA_DV FROM RL_KYTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT ON ADMIN.NHAN_VIEN FROM RL_KYTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE UPDATE ON ADMIN.NHAN_VIEN FROM RL_KYTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT ON ADMIN.BENH_NHAN FROM RL_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE UPDATE ON ADMIN.BENH_NHAN FROM RL_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 2. View cho RL_KYTHUATVIEN
--    TC#4: chỉ thấy dịch vụ được phân công, chỉ sửa KET_QUA
--    TC#5: chỉ thấy/sửa thông tin cá nhân của chính mình
-- =====================================================
CREATE OR REPLACE VIEW ADMIN.V_HSBA_DV_KTV AS
    SELECT MA_HSBA, LOAI_DV, NGAY_DV, MA_KTV, KET_QUA
    FROM   ADMIN.HSBA_DV
    WHERE  MA_KTV = SYS_CONTEXT('USERENV', 'SESSION_USER')
    WITH CHECK OPTION CONSTRAINT CK_V_HSBA_DV_KTV;

CREATE OR REPLACE VIEW ADMIN.V_NHAN_VIEN_SELF AS
    SELECT MA_NV, HO_TEN, PHAI, NGAY_SINH, CMND,
           QUE_QUAN, SDT, VAI_TRO, CHUYEN_KHOA
    FROM   ADMIN.NHAN_VIEN
    WHERE  MA_NV = SYS_CONTEXT('USERENV', 'SESSION_USER')
    WITH CHECK OPTION CONSTRAINT CK_V_NHAN_VIEN_SELF;

GRANT SELECT ON ADMIN.V_HSBA_DV_KTV TO RL_KYTHUATVIEN;
GRANT UPDATE (KET_QUA) ON ADMIN.V_HSBA_DV_KTV TO RL_KYTHUATVIEN;

GRANT SELECT ON ADMIN.V_NHAN_VIEN_SELF TO RL_KYTHUATVIEN;
GRANT UPDATE (QUE_QUAN, SDT) ON ADMIN.V_NHAN_VIEN_SELF TO RL_KYTHUATVIEN;

-- =====================================================
-- 3. View cho RL_BENHNHAN
--    TC#5: bệnh nhân chỉ thấy/sửa thông tin của chính mình
-- =====================================================
CREATE OR REPLACE VIEW ADMIN.V_BENH_NHAN_SELF AS
    SELECT MA_BN, TEN_BN, PHAI, NGAY_SINH, CCCD,
           SO_NHA, TEN_DUONG, QUAN_HUYEN, TINH_TP,
           TIEN_SU_BENH, TIEN_SU_BENH_GD, DI_UNG_THUOC
    FROM   ADMIN.BENH_NHAN
    WHERE  MA_BN = SYS_CONTEXT('USERENV', 'SESSION_USER')
    WITH CHECK OPTION CONSTRAINT CK_V_BENH_NHAN_SELF;

GRANT SELECT ON ADMIN.V_BENH_NHAN_SELF TO RL_BENHNHAN;
GRANT UPDATE (SO_NHA, TEN_DUONG, QUAN_HUYEN, TINH_TP,
              TIEN_SU_BENH, TIEN_SU_BENH_GD, DI_UNG_THUOC)
    ON ADMIN.V_BENH_NHAN_SELF TO RL_BENHNHAN;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Đã tạo view + cấp quyền RBAC cho RL_KYTHUATVIEN.');
    DBMS_OUTPUT.PUT_LINE('Đã tạo view + cấp quyền RBAC cho RL_BENHNHAN.');
    DBMS_OUTPUT.PUT_LINE('=== Hoàn thành RBAC + View cho KTV + BN ===');
END;
/
