-- =====================================================
-- FIX: Dọn dẹp tất cả trước khi chạy lại từ đầu
-- Chạy bằng SYSDBA
-- =====================================================

-- 1. Dọn bảng ở CDB root (đã tạo nhầm lần trước)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE don_thuoc CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE hsba_dv CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE hsba CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE nhan_vien CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE benh_nhan CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

PURGE RECYCLEBIN;

-- 2. Drop user ADMIN nếu tồn tại ở CDB root
BEGIN
    EXECUTE IMMEDIATE 'DROP USER admin CASCADE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 3. Chuyển sang PDB và dọn ở đó luôn
ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin.don_thuoc CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin.hsba_dv CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin.hsba CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin.nhan_vien CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin.benh_nhan CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER admin CASCADE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

PURGE RECYCLEBIN;

-- Giờ chạy: @run_01_as_sysdba.sql
